
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[160] =
    {   0,
        0,    0,   57,   55,    1,    1,   55,   48,   55,   55,
       42,   43,   55,   55,   55,   49,   55,   52,   55,   50,
       36,   26,   35,   46,   55,   47,   55,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   44,   55,
       45,   55,    1,    0,    2,    0,   20,   23,   16,   52,
       18,   19,   40,   17,    0,   33,   38,    0,   37,    0,
       39,   24,   54,    0,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   13,   54,   25,   41,
        0,    0,   51,   21,   22,    0,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,

        0,    0,    0,    0,    0,    0,    0,   34,   53,    0,
       54,   54,   15,   54,   54,   54,   54,   54,    9,   54,
        5,   54,   54,   54,    0,    0,    0,    0,    0,    0,
        0,   54,   54,   54,    6,   54,    8,   54,   11,   54,
       14,   32,   29,   27,   28,   30,   31,    0,   51,    4,
        3,   54,   54,   10,   12,   54,   54,    7,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    6,    7,    1,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,   21,   22,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       23,   24,   25,   26,   27,    1,   28,   29,   30,   31,

       32,   33,   29,   34,   35,   29,   29,   36,   37,   38,
       39,   40,   29,   41,   42,   43,   29,   44,   29,   29,
       29,   29,   45,   46,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   48,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       49,    1,    1,   50,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    2,    2
    } ;

static const flex_int16_t yy_base[166] =
    {   0,
        0,    0,  330,  331,   49,   51,   51,  331,  310,  309,
      331,  331,  308,   41,   42,  331,   44,   44,  310,  331,
       46,  331,   49,  331,  301,  331,  305,   52,   53,   55,
       56,   57,   59,   61,   62,   72,   70,   67,  331,   54,
      331,   48,  104,   97,  331,  285,  331,  331,  331,   94,
      331,  331,  331,  331,  307,  331,  331,  302,  331,  301,
      331,  331,  304,  302,   95,   97,   98,   99,  100,  102,
      104,  108,  118,  125,  121,  127,  128,  129,  331,  331,
      154,  130,  147,  331,  331,  143,  146,  152,  156,  159,
      160,  161,  162,  150,  154,  159,  163,  167,  175,  173,

      260,  258,  257,  256,  255,  254,  282,  281,  331,  265,
      195,  181,  182,  185,  183,  187,  189,  199,  202,  203,
      205,  208,  212,  209,  213,  198,  189,  173,  149,  130,
      241,  227,  226,  228,  229,  231,  232,  233,  236,  246,
      248,  331,  331,  331,  331,  331,  331,  157,  132,  249,
      250,  251,  255,  253,  254,  267,  269,  270,  331,  312,
      134,  117,  115,  315,   75
    } ;

static const flex_int16_t yy_def[166] =
    {   0,
      159,    1,  159,  159,  159,  159,  160,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  161,  161,  161,
      161,  161,  161,  161,  161,  161,   35,   35,  159,  159,
      159,  159,  159,  160,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  162,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  163,  159,  159,
      159,  164,  159,  159,  159,  165,  163,  163,  163,  163,
      163,  163,  163,   66,   66,   66,   66,   66,   66,   66,

      159,  159,  159,  159,  159,  159,  164,  164,  159,  159,
      165,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,  159,  159,  159,  159,  159,  159,
      159,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,  159,  159,  159,  159,  159,  159,  159,  159,   66,
       66,   66,   66,   66,   66,   66,   66,   66,    0,  159,
      159,  159,  159,  159,  159
    } ;

static const flex_int16_t yy_nxt[382] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
        4,    4,   24,   25,   26,   27,    4,   28,   28,   29,
       28,   30,   31,   32,   28,   28,   33,   28,   34,   35,
       36,   37,   28,   38,   39,   40,   41,    4,    4,   42,
       43,   43,   43,   43,   45,   50,   50,   53,   50,   51,
       52,   57,   54,   58,   59,   55,   63,   63,   60,   63,
       63,   63,   79,   63,   46,   63,   63,  111,   64,   64,
       66,   64,   64,   64,   69,   64,   63,   64,   64,   72,
       71,   68,   67,   70,   78,   81,   82,   75,   64,   80,

       45,   76,   73,   74,   77,   43,   43,   65,   50,   63,
       65,   63,   63,   63,   63,   55,   63,   87,   63,   64,
       46,   86,   63,   86,   86,   86,   86,   88,   86,   92,
       86,   94,   63,   93,   86,   63,   65,   91,   89,   63,
       90,   63,   63,   63,   86,  108,  149,   86,   95,   96,
      109,   86,   97,   86,   86,   86,   98,   63,  100,  101,
       63,   83,   99,  102,  103,  104,   63,  105,  110,   86,
       63,  149,   86,   63,   63,   63,   63,  147,   86,  106,
       87,  119,   86,  112,   87,   86,   86,   86,   86,  120,
      114,  118,  116,   87,  113,   87,  146,   87,  121,  117,

       87,  122,  115,   87,   87,   87,  123,  124,   87,   63,
      134,   87,   87,   87,   87,   87,   87,   87,  132,   87,
      145,   86,   87,   87,   87,  133,   87,  135,   87,   87,
       87,  136,   87,   87,  138,   87,  144,  137,   87,   87,
       87,  140,   87,   87,   87,  143,   87,  141,  139,   87,
       87,  148,  148,   87,  150,  149,   87,   87,   87,   87,
      142,   87,   87,   87,  151,  152,   87,   87,   87,   87,
       87,  153,   87,   87,   87,  154,   87,   87,   87,   87,
       87,   87,  157,   87,   87,   87,  131,   87,  155,   87,
       87,   87,   87,  156,   87,   87,   87,   87,  121,   87,

       87,  109,  109,  130,  129,  128,  127,  126,   87,  125,
      158,   87,   44,   44,   44,  107,   63,  107,   63,   85,
       84,   83,   44,   62,   61,   56,   49,   48,   47,  159,
        3,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159
    } ;

static const flex_int16_t yy_chk[382] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    6,    6,    7,   14,   15,   17,   18,   14,
       15,   21,   17,   21,   23,   18,   28,   29,   23,   30,
       31,   32,   40,   33,    7,   34,   35,  165,   28,   29,
       29,   30,   31,   32,   32,   33,   36,   34,   35,   35,
       34,   31,   30,   33,   38,   42,   42,   37,   36,   40,

       44,   37,   35,   36,   37,   43,   43,   38,   50,   65,
       37,   66,   67,   68,   69,   50,   70,  163,   71,  162,
       44,   65,   72,   66,   67,   68,   69,   66,   70,   69,
       71,   71,   73,   70,   72,   75,  161,   68,   66,   74,
       67,   76,   77,   78,   73,   82,  149,   75,   72,   73,
       82,   74,   74,   76,   77,   78,   75,   86,   78,   81,
       87,   83,   76,   81,   81,   81,   88,   81,   83,   86,
       89,  148,   87,   90,   91,   92,   93,  130,   88,   81,
       94,   95,   89,   88,   95,   90,   91,   92,   93,   96,
       90,   94,   92,   97,   89,   95,  129,   98,   97,   93,

       96,   98,   91,  100,   97,   99,   99,  100,   98,  111,
      115,  112,  113,  115,  100,  114,   99,  116,  112,  117,
      128,  111,  112,  113,  115,  114,  114,  116,  116,  118,
      117,  117,  119,  120,  120,  121,  127,  118,  122,  124,
      118,  123,  123,  119,  120,  126,  121,  124,  122,  122,
      124,  131,  131,  123,  132,  131,  133,  132,  134,  135,
      125,  136,  137,  138,  133,  134,  139,  133,  132,  134,
      135,  136,  136,  137,  138,  138,  140,  139,  141,  150,
      151,  152,  153,  154,  155,  153,  110,  140,  140,  141,
      150,  151,  152,  152,  154,  155,  153,  156,  156,  157,

      158,  108,  107,  106,  105,  104,  103,  102,  156,  101,
      157,  158,  160,  160,  160,  164,   64,  164,   63,   60,
       58,   55,   46,   27,   25,   19,   13,   10,    9,    3,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[57] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "as.l"
#line 7 "as.l"
/*
  Analizador Léxico + Sintáctico Descendente Recursivo
  Proyecto: Analizador Sintáctico
  Autores: Franco Ramirez Christian, Pérez Paitán Brent Armando
  Fecha : 2025-11-08

  Descripción:
  - Analizador léxico en Flex que genera tokens y tablas (identificadores,
    literales reales y cadenas).
  - Genera la cadena de átomos (atoms[]) que alimenta el parser recursivo.
  - Contiene un parser descendente recursivo que informa errores sintácticos
    indicando el átomo/token donde aparecieron.
  - Resultado final: impresión de tablas, tokens, cadena de átomos y si el
    programa fuente es sintácticamente correcto.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

/* ---------- Definición de estructuras de tokens/tablas ---------- */
#define MAX_TOKENS 10000
#define MAX_IDENTS 1000
#define MAX_LITSTR 1000
#define MAX_LITREAL 1000

typedef struct {
    int clase;      /* clase léxica */
    char *valor;    /* valor semántico (índice en tabla o ascii) */
    char *etm;      /* lexema original */
} Token;

Token tokens[MAX_TOKENS];
int n_tokens = 0;

/* Tablas */
char *idents[MAX_IDENTS];
int n_idents = 0;

char *litstr[MAX_LITSTR];
int n_litstr = 0;

char *litreal[MAX_LITREAL];
int n_litreal = 0;

/* Clases léxicas */
enum {
    C_PALRES=0,  
    C_INT=1,
    C_ID=2,
    C_OPASIG=3,
    C_SIMB=4,
    C_OPLOG=5,
    C_REAL=6,
    C_CAD=7,
    C_OPARIT=8,
    C_OPREL=9,
};

/* variables para los átomos / parser */
char *atoms = NULL;   
int atom_count = 0;
int atom_pos = 0;
int syntax_errors = 0;

/* funciones auxiliares del parser (prototipos) */
char peek_atom();
void advance_atom();
void syn_error(const char *msg);
void print_error_loc(int pos);
void build_atom_array();
void parse_driver();

/* prototipo de yylex/yyin (proporcionado por flex) */
extern int yylex();
extern FILE *yyin;
extern char *yytext;
extern int yyleng;

/* función auxiliar para clonar strings */
char *strdup_safe(const char *s) {
    if (!s) return NULL;
    char *r = malloc(strlen(s)+1);
    strcpy(r,s);
    return r;
}

/* Añadir identificador a tabla y devolver índice como string */
char *add_ident(const char *s) {
    for (int i=0;i<n_idents;i++) if (strcmp(idents[i], s)==0) {
        char tmp[32]; sprintf(tmp, "%d", i); return strdup_safe(tmp);
    }
    if (n_idents >= MAX_IDENTS) { fprintf(stderr,"Demasiados identificadores\n"); exit(1); }
    idents[n_idents] = strdup_safe(s);
    char tmp[32]; sprintf(tmp, "%d", n_idents);
    n_idents++;
    return strdup_safe(tmp);
}

/* Añadir literal cadena */
char *add_litstr(const char *s) {
    for (int i=0;i<n_litstr;i++) if (strcmp(litstr[i], s)==0) {
        char tmp[32]; sprintf(tmp, "%d", i); return strdup_safe(tmp);
    }
    if (n_litstr >= MAX_LITSTR) { fprintf(stderr,"Demasiados literales cadena\n"); exit(1); }
    litstr[n_litstr] = strdup_safe(s);
    char tmp[32]; sprintf(tmp, "%d", n_litstr);
    n_litstr++;
    return strdup_safe(tmp);
}

/* Añadir literal real */
char *add_litreal(const char *s) {
    for (int i=0;i<n_litreal;i++) if (strcmp(litreal[i], s)==0) {
        char tmp[32]; sprintf(tmp, "%d", i); return strdup_safe(tmp);
    }
    if (n_litreal >= MAX_LITREAL) { fprintf(stderr,"Demasiados literales reales\n"); exit(1); }
    litreal[n_litreal] = strdup_safe(s);
    char tmp[32]; sprintf(tmp, "%d", n_litreal);
    n_litreal++;
    return strdup_safe(tmp);
}

/* Añadir token */
void add_token_int(int clase, const char *valor, const char *lex) {
    if (n_tokens >= MAX_TOKENS) { fprintf(stderr,"Demasiados tokens\n"); exit(1); }
    tokens[n_tokens].clase = clase;
    tokens[n_tokens].valor = valor? strdup_safe(valor) : strdup_safe("");
    tokens[n_tokens].etm = lex? strdup_safe(lex) : strdup_safe("");
    n_tokens++;
}

/* Tablas/Impresión de tokens */
void print_tables() {
    printf("\n=== TOKENS (%d) ===\n", n_tokens);
    for (int i=0;i<n_tokens;i++) {
        printf("%4d)\tclase=%d    valor='%s'\t lex='%s'\n", i, tokens[i].clase, tokens[i].valor, tokens[i].etm);
    }
    printf("\n=== IDENTIFICADORES (%d) ===\n", n_idents);
    for (int i=0;i<n_idents;i++) printf("%4d) %s\n", i, idents[i]);
    printf("\n=== LITERALES CADENA (%d) ===\n", n_litstr);
    for (int i=0;i<n_litstr;i++) printf("%4d) \"%s\"\n", i, litstr[i]);
    printf("\n=== LITERALES REALES (%d) ===\n", n_litreal);
    for (int i=0;i<n_litreal;i++) printf("%4d) %s\n", i, litreal[i]);
}

/* ---------- convertidor token -> átomo char ---------- */
/* Ajusta los caracteres de átomo para que coincidan con el enunciado. */
char token_to_atom(int clase, const char *valor, const char *lex) {
    if (clase == C_PALRES) {
        int code = atoi(valor);
        switch(code) {
            case 0: return 'c'; /* cadena */
            case 1: return 'k'; /* caso */
            case 2: return 'e'; /* entero */
            case 3: return 'f'; /* flotante/real */
            case 4: return 'h'; /* hacer */
            case 5: return 'm'; /* mientras */
            case 6: return 'o'; /* ocaso */
            case 7: return 'p'; /* para */
            case 8: return 't'; /* predet */
            case 9: return 'x'; /* salir */
            case 10: return 'q';/* select */
            case 11: return 'y';/* si */
            case 12: return 'v';/* vacio */
        }
    } else if (clase == C_INT) return 'i';
    else if (clase == C_ID) return 'a';
    else if (clase == C_REAL) return 'r';
    else if (clase == C_CAD) return 's';
    else if (clase == C_SIMB) {
        /* símbolos: operadores y puntuación: usamos el primer carácter del lexema */
        if (lex && lex[0]) return lex[0];
    } else if (clase == C_OPARIT) {
        int code = atoi(valor);
        switch(code) {
            case 0: return '+'; case 1: return '-'; case 2: return '*';
            case 3: return '/'; case 4: return '¬'; case 5: return '%';
        }
    } else if (clase == C_OPASIG) {
        int code = atoi(valor);
        /* mapear códigos de op asignación  */
        switch(code) {
            case 0: return '=';   /* = */
            case 1: return 'd';   /* *= */
            case 2: return 'j';   /* /= */
            case 3: return 'u';   /* += */
            case 4: return '¡';   /* -= */
            case 5: return 'w';   /* %= */
            case 6: return '<';   /* <<= */
            case 7: return '>';   /* >>= */
            case 8: return '&';   /* &= */
            case 9: return '^';   /* ^= */
            case 10: return '|';  /* |= */
        }
    } else if (clase == C_OPREL) {
        int code = atoi(valor);
        /* códigos: 0::,1¿:,2> ,3<,4>:,5<: */
        switch(code) {
            case 0: return 'g'; case 1: return '¿'; case 2: return 'z';
            case 3: return 'l'; case 4: return '!'; case 5: return 'n';
        }
    } else if (clase == C_OPLOG) {
        int code = atoi(valor);
        /* 0 AND,1 OR,2 NOT  */
        switch(code) {
            case 0: return '\\'; case 1: return 'b'; case 2: return '#';
        }
    }
}

/* Construye atoms[] a partir de tokens[] */
void build_atom_array() {
    if (n_tokens == 0) { atoms = strdup_safe(""); atom_count = 0; return; }
    atoms = malloc(n_tokens + 1);
    for (int i=0;i<n_tokens;i++) {
        atoms[i] = token_to_atom(tokens[i].clase, tokens[i].valor, tokens[i].etm);
    }
    atoms[n_tokens] = '\0';
    atom_count = n_tokens;
}

/* ---------- apoyo para el parser (peek/advance/errores) ---------- */
char peek_atom() {
    if (!atoms) return 0;
    if (atom_pos >= atom_count) return 0;
    return atoms[atom_pos];
}
void advance_atom() {
    if (atom_pos < atom_count) atom_pos++;
}
void syn_error(const char *msg) {
    fprintf(stderr,"Error sintáctico (pos %d): %s. ", atom_pos, msg);
    print_error_loc(atom_pos);
    syntax_errors++;
    /* intento de recuperación básico: avanzar uno */
    if (atom_pos < atom_count) atom_pos++;
}
void print_error_loc(int pos) {
    if (pos < 0 || pos >= n_tokens) {
        fprintf(stderr,"(posición fuera de rango %d)\n", pos);
        return;
    }
    fprintf(stderr,"[Token %d: '%s']\n", pos, tokens[pos].etm);
}

/* ------------------ Prototipos de todas las funciones del parser -------------- */

void Program(); void otraFunc(); void Func(); void listArg(); void otroArg();
void cuerpo(); void listaDec(); void sent_decl(); void tipo_fn();
void lista_id(); void resto_lista_id(); void asig_val(); void constante_fn();
void E(); void Eprime(); void T(); void Tprime(); void F(); void LlamaFunc();
void asig(); void opAsig_fn(); void expRel(); void opRel_fn(); void exprLog();
void exprV(); void opLog_fn(); void Sent_fn(); void props_fn(); void hacerM();
void condicion_fn(); void si_fn(); void finalsi(); void ocaso_fn(); void para_fn();
void expr_fn(); void salir_fn(); void valRet_fn(); void select_fn(); void siguiente_fn();
void listP_fn(); void Param_fn();

/* ------------------ Implementación de las funciones del parser --------------- */

void Program() {
    char p = peek_atom();
    if (p=='c' || p=='e' || p=='f' || p=='v') {
        Func();
        otraFunc();
    } else {
        syn_error("inicio de Program (se esperaba c/e/f/v)");
    }
}

void otraFunc() {
    char p = peek_atom();
    if (p=='c' || p=='e' || p=='f' || p=='v') {
        Func();
        otraFunc();
    } else {
        /* epsilon/fin */
        return;
    }
}

void Func() {
    char p = peek_atom();
    if (p=='c' || p=='e' || p=='f' || p=='v') {
        tipo_fn();
        if (peek_atom()=='a') advance_atom(); else syn_error("identificador 'a' en Func");
        if (peek_atom()=='(') advance_atom(); else syn_error("'(' en Func");
        listArg();
        if (peek_atom()==')') advance_atom(); else syn_error("')' en Func");
        if (peek_atom()=='[') advance_atom(); else syn_error("'[' inicio cuerpo");
        cuerpo();
        if (peek_atom()==']') advance_atom(); else syn_error("']' fin cuerpo");
    } else {
        syn_error("Func (tipo esperado)");
    }
}

void listArg() {
    char p = peek_atom();
    if (p=='c' || p=='e' || p=='f' || p=='v') {
        tipo_fn();
        if (peek_atom()=='a') advance_atom(); else syn_error("'a' en listArg");
        otroArg();
    } else if (p==')') {
        return;
    } else {
        syn_error("listArg (tipo o ')')");
    }
}

void otroArg() {
    char p = peek_atom();
    if (p==';') {
        advance_atom();
        tipo_fn();
        if (peek_atom()=='a') advance_atom(); else syn_error("'a' en otroArg");
        otroArg();
    } else if (p==')') {
        return;
    } else {
        /* epsilon */
        return;
    }
}

void cuerpo() {
    listaDec();
    props_fn();
}

void listaDec() {
    char p = peek_atom();
    if (p=='c' || p=='e' || p=='f' || p=='v') {
        sent_decl();
        listaDec();
    } else {
        return;
    }
}

void sent_decl() {
    if (peek_atom()=='c' || peek_atom()=='e' || peek_atom()=='f' || peek_atom()=='v') {
        tipo_fn();
        lista_id();
        if (peek_atom()=='.') advance_atom(); else syn_error("'.' despues de declaracion");
    } else {
        syn_error("sent_decl (tipo esperado)");
    }
}

void tipo_fn() {
    char p = peek_atom();
    if (p=='e' || p=='f' || p=='c' || p=='v') {
        advance_atom();
    } else {
        syn_error("tipo (e/f/c/v)");
    }
}

void lista_id() {
    if (peek_atom()=='a') {
        advance_atom();
        asig_val();
        resto_lista_id();
    } else {
        syn_error("lista_id (se esperaba 'a')");
    }
}

void resto_lista_id() {
    char p = peek_atom();
    if (p==';') {
        advance_atom();
        lista_id();
    } else {
        return;
    }
}

void asig_val() {
    char p = peek_atom();
    if (p=='=') {
        advance_atom();
        constante_fn();
    } else {
        return;
    }
}

void constante_fn() {
    char p = peek_atom();
    if (p=='i' || p=='r' || p=='s') advance_atom();
    else syn_error("constante (i,r,s)");
}

/* ---------------- EXPRESIONES ---------------- */

void E() {
    char p = peek_atom();
    if (p==0) { syn_error("E (fin inesperado)"); return; }
    if (p=='(' || p=='a' || p=='i' || p=='r' || p=='s' || p=='$') {
        T();
        Eprime();
    } else {
        syn_error("inicio de expresion (E)");
    }
}

void Eprime() {
    char p = peek_atom();
    if (p=='+') {
        advance_atom();
        T();
        Eprime();
    } else if (p=='-') {
        advance_atom();
        T();
        Eprime();
    } else {
        return;
    }
}

void T() {
    char p = peek_atom();
    if (p=='(' || p=='a' || p=='i' || p=='r' || p=='s' || p=='$') {
        F();
        Tprime();
    } else {
        syn_error("inicio de termino (T)");
    }
}

void Tprime() {
    char p = peek_atom();
    if (p=='*') {
        advance_atom(); F(); Tprime();
    } else if (p=='/') {
        advance_atom(); F(); Tprime();
    } else if (p=='%') {
        advance_atom(); F(); Tprime();
    } else if (p=='^') {
        advance_atom(); F(); Tprime();
    } else {
        return;
    }
}

void F() {
    char p = peek_atom();
    if (p=='(') {
        advance_atom(); E();
        if (peek_atom()==')') advance_atom(); else syn_error("')' despues de (E)");
    } else if (p=='a') {
        advance_atom();
    } else if (p=='i' || p=='r' || p=='s') {
        advance_atom();
    } else if (p=='$') {
        LlamaFunc();
    } else {
        syn_error("factor F");
    }
}

void LlamaFunc() {
    if (peek_atom()=='$') {
        advance_atom();
        if (peek_atom()=='a') advance_atom(); else syn_error("'a' despues de $ en llamada");
        if (peek_atom()=='(') advance_atom(); else syn_error("'(' en llamada");
        listP_fn();
        if (peek_atom()==')') advance_atom(); else syn_error("')' fin llamada");
    } else {
        syn_error("LlamaFunc ($ esperado)");
    }
}

/* ---------------- ASIGNACIONES y OPERADORES ---------------- */

void asig() {
    if (peek_atom()=='a') {
        advance_atom();
        opAsig_fn();
        E();
        if (peek_atom()=='.') advance_atom(); else syn_error("'.' al final de asignacion");
    } else {
        syn_error("asig (a esperado)");
    }
}

void opAsig_fn() {
    char p = peek_atom();
    if (p=='='||p=='d'||p=='j'||p=='u'||p=='v'||p=='w'||p=='<'||p=='>'||p=='&'||p=='^'||p=='|') {
        advance_atom();
    } else {
        syn_error("operador asignacion (=, d, j, u, v, w, <, >, &, ^, |)");
    }
}

/* ---------------- RELACIONALES / LOGICOS ---------------- */

void expRel() {
    if (peek_atom()=='[') {
        advance_atom();
        E();
        opRel_fn();
        E();
        if (peek_atom()==']') advance_atom(); else syn_error("']' en expRel");
    } else {
        syn_error("'[' inicio expRel");
    }
}

void opRel_fn() {
    char p = peek_atom();
    if (p == 'g' || p == 'z' || p == 'l' || p == '!' || p == 'n' || (unsigned char)p == 0xBF)    advance_atom();
    else syn_error("opRel (g,¿,z,l,!,n)");
}

void exprLog() {
    char p = peek_atom();
    if (p=='#') {
        advance_atom();
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' despues de #");
        exprV();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' despues de exprV");
    } else if (p=='{') {
        advance_atom();
        expRel();
        opLog_fn();
        expRel();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' fin exprLog");
    } else {
        syn_error("exprLog (# o {)");
    }
}

void exprV() {
    char p = peek_atom();
    if (p=='(' || p=='a' || p=='i' || p=='r' || p=='s' || p=='$') {
        E();
    } else if (p=='[') {
        expRel();
    } else {
        syn_error("exprV (E o expRel)");
    }
}

void opLog_fn() {
    char p = peek_atom();
    if (p=='\\' || p=='b') advance_atom();
    else syn_error("opLog (\\ o b)");
}

/* ---------------- SENTENCIAS / BLOQUES ---------------- */

void Sent_fn() {
    char p = peek_atom();
    if (p=='a') { asig(); }
    else if (p=='h') { hacerM(); }
    else if (p=='y') { si_fn(); }
    else if (p=='p') { para_fn(); }
    else if (p=='x') { salir_fn(); }
    else if (p=='q') { select_fn(); }
    else { syn_error("inicio de Sent (a/h/y/p/x/q)"); }
}

void props_fn() {
    char p = peek_atom();
    if (p=='a' || p=='h' || p=='y' || p=='p' || p=='x' || p=='q') {
        Sent_fn();
        props_fn();
    } else {
        return;
    }
}

void hacerM() {
    if (peek_atom()=='h') {
        advance_atom();
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' despues de h");
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' en hacerM");
        if (peek_atom()=='m') advance_atom(); else syn_error("'m' despues del bloque de hacer");
        condicion_fn();
        if (peek_atom()=='.') advance_atom(); else syn_error("'.' despues de hacerM");
    } else syn_error("hacerM (h esperado)");
}

void condicion_fn() {
    char p = peek_atom();
    if (p=='[') expRel();
    else if (p=='#' || p=='{') exprLog();
    else syn_error("condicion ([ o # o {)");
}

void si_fn() {
    if (peek_atom()=='y') {
        advance_atom();
        condicion_fn();
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' despues de condicion en si");
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' fin bloque si");
        finalsi();
    } else syn_error("si (y esperado)");
}

void finalsi() {
    char p = peek_atom();
    if (p=='o') {
        advance_atom();
        ocaso_fn();
    } else {
        return;
    }
}

void ocaso_fn() {
    char p = peek_atom();
    if (p=='y') si_fn();
    else if (p=='{') {
        advance_atom();
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' en ocaso");
    } else syn_error("ocaso (y o {)");
}

void para_fn() {
    if (peek_atom()=='p') {
        advance_atom();
        if (peek_atom()=='(') advance_atom(); else syn_error("'(' despues de p");
        expr_fn();
        if (peek_atom()==';') advance_atom(); else syn_error("';' despues de expr en para");
        condicion_fn();
        if (peek_atom()==';') advance_atom(); else syn_error("';' despues de condicion en para");
        expr_fn();
        if (peek_atom()==')') advance_atom(); else syn_error("')' en para");
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' inicio bloque para");
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' fin para");
    } else syn_error("para (p esperado)");
}

void expr_fn() {
    if (peek_atom()=='a') {
        advance_atom();
        opAsig_fn();
        E();
    } else syn_error("expr (a esperado)");
}

void salir_fn() {
    if (peek_atom()=='x') {
        advance_atom();
        valRet_fn();
        if (peek_atom()=='.') advance_atom(); else syn_error("'.' despues de salir");
    } else syn_error("salir (x esperado)");
}

void valRet_fn() {
    char p = peek_atom();
    if (p=='(' || p=='a' || p=='i' || p=='r' || p=='s' || p=='$') E();
    else return;
}

void select_fn() {
    if (peek_atom()=='q') {
        advance_atom();
        if (peek_atom()=='(') advance_atom(); else syn_error("'(' en select");
        if (peek_atom()=='a') advance_atom(); else syn_error("'a' en select");
        if (peek_atom()==')') advance_atom(); else syn_error("')' en select");
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' inicio select");
        if (peek_atom()=='k') {
            advance_atom();
            if (peek_atom()=='i') advance_atom(); else syn_error("'i' despues de k en select");
            if (peek_atom()=='{') advance_atom(); else syn_error("'{' en caso select");
            props_fn();
            if (peek_atom()=='}') advance_atom(); else syn_error("'}' fin caso");
            siguiente_fn();
        } else syn_error("'k' en select");
    } else syn_error("select (q esperado)");
}

void siguiente_fn() {
    char p = peek_atom();
    if (p=='k') {
        advance_atom();
        if (peek_atom()=='i') advance_atom(); else syn_error("'i' despues de k en siguiente");
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' en siguiente");
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' fin siguiente");
        siguiente_fn();
    } else if (p=='}') {
        advance_atom();
        return;
    } else if (p=='t') {
        advance_atom();
        if (peek_atom()=='{') advance_atom(); else syn_error("'{' despues de t en siguiente");
        props_fn();
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' despues de t");
        if (peek_atom()=='}') advance_atom(); else syn_error("'}' cierre select");
        return;
    } else {
        syn_error("siguiente (k, } o t)");
    }
}

void listP_fn() {
    char p = peek_atom();
    if (p==')') return;
    else if (p=='(' || p=='a' || p=='i' || p=='r' || p=='s' || p=='$') {
        E();
        Param_fn();
    } else syn_error("listP (parametros)");
}

void Param_fn() {
    char p = peek_atom();
    if (p==';') {
        advance_atom();
        E();
        Param_fn();
    } else return;
}

#line 1331 "lex.yy.c"
/* ---------- REGLAS DE FLEX -> ANALIZADOR LEXICO ---------- */
#line 1333 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 743 "as.l"

#line 1552 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 160 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 331 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 744 "as.l"
{ /* ignorar espacios y nueva línea */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 746 "as.l"
{ /* comentario: ignorar */ }  
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 748 "as.l"
{ add_token_int(C_PALRES, "2", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 749 "as.l"
{ add_token_int(C_PALRES, "0", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 750 "as.l"
{ add_token_int(C_PALRES, "3", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 751 "as.l"
{ add_token_int(C_PALRES, "4", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 752 "as.l"
{ add_token_int(C_PALRES, "5", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 753 "as.l"
{ add_token_int(C_PALRES, "6", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 754 "as.l"
{ add_token_int(C_PALRES, "7", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 755 "as.l"
{ add_token_int(C_PALRES, "8", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 756 "as.l"
{ add_token_int(C_PALRES, "9", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 757 "as.l"
{ add_token_int(C_PALRES, "10", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 758 "as.l"
{ add_token_int(C_PALRES, "11", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 759 "as.l"
{ add_token_int(C_PALRES, "12", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 760 "as.l"
{ add_token_int(C_PALRES, "1", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 762 "as.l"
{ add_token_int(C_OPASIG, "1", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 763 "as.l"
{ add_token_int(C_OPASIG, "2", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 764 "as.l"
{ add_token_int(C_OPASIG, "3", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 765 "as.l"
{ add_token_int(C_OPASIG, "4", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 766 "as.l"
{ add_token_int(C_OPASIG, "5", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 767 "as.l"
{ add_token_int(C_OPASIG, "6", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 768 "as.l"
{ add_token_int(C_OPASIG, "7", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 769 "as.l"
{ add_token_int(C_OPASIG, "8", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 770 "as.l"
{ add_token_int(C_OPASIG, "9", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 771 "as.l"
{ add_token_int(C_OPASIG, "10", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 772 "as.l"
{ add_token_int(C_OPASIG, "0", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 774 "as.l"
{ add_token_int(C_OPARIT, "0", yytext); } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 775 "as.l"
{ add_token_int(C_OPARIT, "1", yytext); } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 776 "as.l"
{ add_token_int(C_OPARIT, "2", yytext); } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 777 "as.l"
{ add_token_int(C_OPARIT, "3", yytext); } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 778 "as.l"
{ add_token_int(C_OPARIT, "4", yytext); } 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 779 "as.l"
{ add_token_int(C_OPARIT, "5", yytext); } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 781 "as.l"
{ add_token_int(C_OPREL, "0", yytext); } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 782 "as.l"
{ add_token_int(C_OPREL, "1", yytext); } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 783 "as.l"
{ add_token_int(C_OPREL, "2", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 784 "as.l"
{ add_token_int(C_OPREL, "3", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 785 "as.l"
{ add_token_int(C_OPREL, "4", yytext); } 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 786 "as.l"
{ add_token_int(C_OPREL, "5", yytext); } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 788 "as.l"
{ add_token_int(C_OPLOG, "0", yytext); } 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 789 "as.l"
{ add_token_int(C_OPLOG, "1", yytext); } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 790 "as.l"
{ add_token_int(C_OPLOG, "2", yytext); } 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 792 "as.l"
{ add_token_int(C_SIMB, "40", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 793 "as.l"
{ add_token_int(C_SIMB, "41", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 794 "as.l"
{ add_token_int(C_SIMB, "123", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 795 "as.l"
{ add_token_int(C_SIMB, "125", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 796 "as.l"
{ add_token_int(C_SIMB, "91", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 797 "as.l"
{ add_token_int(C_SIMB, "93", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 798 "as.l"
{ add_token_int(C_SIMB, "36", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 799 "as.l"
{ add_token_int(C_SIMB, "46", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 800 "as.l"
{ add_token_int(C_SIMB, "59", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 802 "as.l"
{
                                char *idx = add_litreal(yytext);
                                add_token_int(C_REAL, idx, yytext);
                            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 806 "as.l"
{
                                add_token_int(C_INT, yytext, yytext);
                            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 809 "as.l"
{
                                /* quitar los simbolos de cadena (¿,?) al almacenar */
                                int L = yyleng;
                                char *tmp = malloc(L-1);
                                if (!tmp) { fprintf(stderr,"malloc fallo\n"); exit(1); }
                                strncpy(tmp, yytext+1, L-2); tmp[L-2]='\0';
                                char *idx = add_litstr(tmp);
                                free(tmp);
                                add_token_int(C_CAD, idx, yytext);
                            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 820 "as.l"
{
                                char *idx = add_ident(yytext);
                                add_token_int(C_ID, idx, yytext);
                            }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 825 "as.l"
{ fprintf(stderr,"ERROR LEX: caracter no reconocido '%s' (se ignora)\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 827 "as.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1918 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 160 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 160 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 159);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 827 "as.l"


/* ---------- Driver del Parser / main ---------- */

void parse_driver() {
    /* construir atoms y lanzar parser */
    build_atom_array();
    atom_pos = 0;
    syntax_errors = 0;

    printf("\n=== CADENA DE ATOMOS (length=%d) ===\n", atom_count);
    for (int i = 0; i < atom_count; ++i) printf("%c", atoms[i]);
    printf("\n\n=== INICIO PARSE ===\n");

    Program();

    if (syntax_errors == 0 && atom_pos >= atom_count) {
        printf("\nEl programa es sintácticamente correcto (sin errores detectados).\n");
    } else {
        printf("\nParse finalizado con %d errores sintácticos. atom_pos=%d atom_count=%d\n", syntax_errors, atom_pos, atom_count);
    }
}

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr,"Uso: %s <archivo_fuente>\n", argv[0]);
        return 1;
    }
    FILE *f = fopen(argv[1],"r");
    if (!f) { perror("abrir archivo fuente"); return 1; }
    yyin = f;
    /* ejecutar lexer y llenar tablas */
    yylex();
    fclose(f);

    /* imprimir tablas iniciales y tokens */
    print_tables();

    /* construir cadena de átomos y ejecutar parser */
    parse_driver();

    return 0;
}
